# Playing around with data

## Food Inspection

In [1]:
from senpai.food_insp import download_csv

In [2]:
import pandas as pd

In [13]:
df = pd.read_csv("./food_insp.csv", dtype=object)

In [14]:
df.columns.values

array(['businessname', 'dbaname', 'legalowner', 'namelast', 'namefirst',
       'licenseno', 'issdttm', 'expdttm', 'licstatus', 'licensecat',
       'descript', 'result', 'resultdttm', 'violation', 'viollevel',
       'violdesc', 'violdttm', 'violstatus', 'statusdate', 'comments',
       'address', 'city', 'state', 'zip', 'property_id', 'location'],
      dtype=object)

In [37]:
# Project to select only the column we wants
DF = df[["businessname", "licenseno", "violstatus", "address", "city", "state", "zip", "property_id", "location"]]

# Remove the row which has an empty value [x for row in table for x in row if x] 
DF = DF.dropna()

# Select all the Fail violations 
DF = DF[DF["violstatus"] == "Fail"]

# Count violations per restaurant
VC = DF.groupby("licenseno").count()

DF_R = DF.set_index("licenseno")[["businessname", "address", "city", "state", "zip", "location"]]
DF_R["violation_count"] = VC["violstatus"]
DF_R = DF_R.drop_duplicates()

DF_R.index.names = ["_id"]

In [38]:
DF_R.sort_values("violation_count")

,businessname,address,city,state,zip,location,violation_count
_id,,,,,,,
173330,El Triunfo Restaurant / Ali Baba,147 E Berkeley ST,Roxbury,MA,02118,"(42.343500000, -71.064800000)",1
22769,CONVENIENT CORNER,1688 Dorchester AVE,Dorchester,MA,02122,"(42.292531000, -71.062241000)",1
19958,REBECCA'S CAFE,411 Brookline AV,Boston,MA,02115,"(42.338823000, -71.107611000)",1
373358,Sebastians Cafe,1 Harborside DR,East Boston,MA,02128,"(42.363408000, -71.025698000)",1
68152,Conte 8,2597 Beacon ST,Brighton,MA,02135,"(42.336249000, -71.166434000)",1
22652,Whittier Health Pharmacy Inc.,1123 Tremont ST,Boston,MA,02115,"(42.335598000, -71.087810000)",1
68151,Conte 7,2597 Beacon ST,Brighton,MA,02135,"(42.336249000, -71.166434000)",1
27957,Bed Bath Beyond...,8 Allstate RD,Dorchester,MA,02125,"(42.326560000, -71.061690000)",1
22007,HART LIQUORS INC.,644 American Legion HWY,Roslindale,MA,02131,"(42.284034000, -71.110859000)",1
362447,Rabottini's Pizza,182 Western AVE,Allston,MA,02134,"(42.362961000, -71.129376000)",1
25338,Mullin's Tavern,289 Dorchester ST,South Boston,MA,02127,"(42.332022000, -71.052758000)",1
74972,BELLA DREW'S CAFE,26 Province ST,Boston,MA,02108,"(42.357172000, -71.059651000)",1
20943,MURPHY'S LIQUORS,4339 Washington ST,Roslindale,MA,02131,"(42.283362000, -71.131669000)",1
57528,Boston Wine Exchange,181 Devonshire ST,Boston,MA,02110,"(42.356053000, -71.057513000)",1
126288,Beacon Hill Gourmet,65 Charles ST,Boston,MA,02114,"(42.358060000, -71.070210000)",1
20991,Beacon Hill Athletic Club,3 Hancock ST,Boston,MA,02114,"(42.360978000, -71.064668000)",1
120875,Beacon Cafe @Univ. of Mass Boston,100 William T Morrissey BLVD,Dorchester,MA,02125,"(42.313144000, -71.038947000)",1
25437,T J Maxx (No. 814),350 Washington ST,Boston,MA,02110,"(42.356390000, -71.058970000)",1
68089,Concession Stand North East,415 Summer ST,Boston,MA,02210,"(42.344449000, -71.044821000)",1
309673,Boston Winter Market Village,1 City Hall PZ,Boston,MA,02201,"(42.360116000, -71.057900000)",1
19566,CAFE GRAFFITI,307 Hanover ST,Boston,MA,02113,"(42.363880000, -71.054160000)",1
314698,Publico,11 Dorchester ST,South Boston,MA,02127,"(42.337210000, -71.043750000)",1
140819,Exodus Bagels,196 Quincy ST,Dorchester,MA,02125,"(42.313161000, -71.074241000)",1
68144,Conte 1,2597 Beacon ST,Brighton,MA,02135,"(42.336249000, -71.166434000)",1
89905,Concession 1,4 Jersey St,Boston,MA,02215,"(42.346723000, -71.098680000)",1
168067,Lalito's Liquors,11 Bennington ST,East Boston,MA,02128,"(42.375018000, -71.038180000)",1
23754,THE FOUNDATION LOUNGE,500 Commonwealth AVE,Boston,MA,02215,"(42.348521000, -71.095099000)",1
34219,I Party No. 69,8 Allstate RD,Dorchester,MA,02125,"(42.326560000, -71.061690000)",1
23617,Travel Traders,64 Arlington ST,Boston,MA,02116,"(42.350707000, -71.069921000)",1
158961,Starbucks Coffee,305 Congress ST,Boston,MA,02210,"(42.351231000, -71.050594000)",1
...,...,...,...,...,...,...,...
23517,SHANGHAI GATEWAY RESTAURANT,204 Harvard AVE,Allston,MA,02134,"(42.349958000, -71.130478000)",272
23387,Seoul,156 Cambridge ST,Boston,MA,02114,"(42.360978000, -71.064668000)",272
18493,China Pearl Restaurant,9 Tyler ST,Boston,MA,02111,"(42.351085000, -71.060788000)",272
33361,IL MONDO,682 Huntington AVE,Boston,MA,02120,"(42.334854000, -71.102439000)",274
21227,CAFE 1010,1010 Massachusetts AV,Roxbury,MA,02118,"(42.327867000, -71.067270000)",276
20104,THE BARKING CRAB,88 Sleeper ST,Boston,MA,02210,"(42.353895000, -71.048576000)",276
31818,Yanes Burrito's,3492 Washington ST,Jamaica Plain,MA,02130,"(42.306280000, -71.107430000)",277
19901,MERENGUE RESTAURANT,156 Blue Hill AVE,Roxbury,MA,02119,"(42.319179000, -71.077549000)",284
22022,CHUNG WAH,199 Bowdoin ST,Dorchester,MA,02122,"(42.305090000, -71.068190000)",285
20157,PARAMOUNT,44 Charles ST,Boston,MA,02114,"(42.357240000, -71.070269000)",291
74662,Edu and Den's Restaurant,637 River ST,Mattapan,MA,02126,"(42.265164000, -71.099382000)",297
22388,CHART HOUSE,60 Long WHF,Boston,MA,02110,"(42.360178000, -71.049411000)",304
29252,Arizona B B Q,2360 Washington ST,Roxbury,MA,02119,"(42.329370000, -71.084460000)",306
20942,ORIENTAL HOUSE,560 Washington ST,Dorchester,MA,02124,"(42.292072000, -71.071521000)",311
22574,Genki Ya of Boston,232 Tremont ST,Boston,MA,02116,"(42.351219000, -71.064646000)",315
22464,BALE RESTAURANT,1052 Dorchester AVE,Dorchester,MA,02125,"(42.314791000, -71.056611000)",321
30908,Pin Bochinche Restaurant,3160 Washington ST,Jamaica Plain,MA,02130,"(42.313579000, -71.100251000)",324
34592,Villa Sombrero Cafe,554A Dudley ST,Dorchester,MA,02125,"(42.321300000, -71.071990000)",329
20637,EL CHALAN,405 Chelsea ST,East Boston,MA,02128,"(42.379767000, -71.027000000)",334
20071,Yely's Coffee Shop,284 Centre ST,Jamaica Plain,MA,02130,"(42.322770000, -71.102040000)",337
20803,AQUITAINE,569 Tremont ST,Roxbury,MA,02118,"(42.343801000, -71.072350000)",338
23526,CANTON HOUSE,6 Hancock ST,Dorchester,MA,02125,"(42.315595000, -71.065919000)",345
19486,Saints Diner,572 Washington ST,Dorchester,MA,02124,"(42.291590000, -71.071470000)",347
22700,DAYIB CAFE,722 Shawmut AVE,Roxbury,MA,02119,"(42.332783000, -71.083221000)",348
21037,India Quality,484 Commonwealth AVE,Boston,MA,02215,"(42.348540000, -71.094220000)",351
20857,EMPIRE GARDEN,686 Washington ST,Boston,MA,02111,"(42.351311000, -71.062640000)",363
31241,Anshur Restauruant,291 Roxbury ST,Roxbury,MA,02119,"(42.330410000, -71.094300000)",366
18686,Black Rose,160 State ST,Boston,MA,02109,"(42.359440000, -71.053790000)",380
23987,The Real Deal,1882 Centre ST,West Roxbury,MA,02132,"(42.285670000, -71.155480000)",485
24748,Durgin Park Restaurant,300 Faneuil Hall Marketplace,Boston,MA,02109,"(42.360036000, -71.056253000)",485

In [7]:
df.dropnan(0)

0         Fail
1         Fail
2         Fail
3         Fail
4         Fail
5         Fail
6         Fail
7         Fail
8         Fail
9         Fail
10        Fail
11        Fail
12        Fail
13        Fail
14        Fail
15        Fail
16        Fail
17        Fail
18        Fail
19        Fail
20         NaN
21        Fail
22        Fail
23        Fail
24        Fail
25        Fail
26        Fail
27        Fail
28        Fail
29        Fail
          ...
562396    Pass
562397    Pass
562398    Pass
562399    Pass
562400    Pass
562401    Pass
562402    Pass
562403    Pass
562404    Pass
562405    Pass
562406    Pass
562407    Pass
562408    Pass
562409    Pass
562410    Pass
562411    Pass
562412    Pass
562413    Pass
562414    Pass
562415    Pass
562416    Pass
562417    Pass
562418    Pass
562419    Pass
562420    Pass
562421    Pass
562422     NaN
562423     NaN
562424     NaN
562425    Pass
Name: violstatus, Length: 562426, dtype: object

In [9]:
df.groupby("licenseno").count()

,businessname,dbaname,legalowner,namelast,namefirst,issdttm,expdttm,licstatus,licensecat,descript,...,violdttm,violstatus,statusdate,comments,address,city,state,zip,property_id,location
licenseno,,,,,,,,,,,,,,,,,,,,,
54,2,0,0,2,2,2,2,2,2,2,...,2,0,0,2,2,2,2,2,0,0
4032,94,0,0,94,94,94,94,94,94,94,...,94,91,29,94,94,94,94,94,0,0
4036,116,0,0,116,116,116,116,116,116,116,...,116,110,41,116,116,116,116,116,116,116
17602,24,24,24,24,24,24,24,24,24,24,...,24,14,6,24,24,24,24,24,24,24
17603,16,16,16,16,16,16,16,16,16,16,...,16,12,4,16,16,16,16,16,16,16
17605,1,1,0,1,1,1,1,1,1,1,...,1,0,0,1,1,1,1,1,0,0
17606,9,0,9,9,9,9,9,9,9,9,...,9,4,2,9,9,9,9,9,9,9
17607,10,10,0,10,10,10,10,10,10,10,...,10,0,0,10,10,10,10,10,0,0
17608,1,0,1,1,1,1,1,1,1,1,...,1,0,0,1,1,1,1,1,1,1
17609,40,0,0,40,40,40,40,40,40,40,...,40,28,11,40,40,40,40,40,40,40
17610,46,0,0,46,46,46,46,46,46,46,...,46,36,15,46,46,46,46,46,46,46
17611,154,0,154,154,154,154,154,154,154,154,...,154,148,67,154,154,154,154,154,154,154
17612,13,13,0,13,13,13,13,13,13,13,...,13,10,0,13,13,13,13,13,0,0
17613,47,0,47,47,47,47,47,47,47,47,...,47,27,13,47,47,47,47,47,0,0
17614,5,5,5,5,5,5,5,5,5,5,...,5,1,0,5,5,5,5,5,5,5
17615,55,55,55,55,55,55,55,55,55,55,...,55,52,23,55,55,55,55,55,55,55
17616,19,19,19,19,19,19,19,19,19,19,...,19,16,1,19,19,19,19,19,19,19
18006,33,0,33,33,33,33,33,33,33,33,...,33,22,10,33,33,33,33,33,0,0
18009,258,0,258,258,258,258,258,258,258,258,...,258,255,94,258,258,258,258,258,0,0
18011,21,0,21,21,21,21,21,21,21,21,...,21,8,2,21,21,21,21,21,21,21
18013,263,0,263,263,263,263,263,263,263,263,...,263,257,119,263,263,263,263,263,263,263
18015,186,0,186,186,186,186,186,186,186,186,...,186,182,84,186,186,186,186,186,186,186
18017,1,0,1,1,1,1,1,1,1,1,...,1,0,0,1,1,1,1,1,1,1
18019,89,0,89,89,89,89,89,89,89,89,...,89,85,25,89,89,89,89,89,0,0
18021,81,0,81,81,81,81,81,81,81,81,...,81,75,34,81,81,81,81,81,81,81
18022,421,0,421,421,421,421,421,421,421,421,...,421,418,161,421,421,421,421,421,0,0
18025,336,0,0,336,336,336,336,336,336,336,...,336,332,133,336,336,336,336,336,336,336
18026,64,0,64,64,64,64,64,64,64,64,...,64,55,25,64,64,64,64,64,64,64
18029,2,0,2,2,2,2,2,2,2,2,...,2,0,0,2,2,2,2,2,0,0
18030,22,0,22,22,22,22,22,22,22,22,...,22,16,5,22,22,22,22,22,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383007,1,0,0,1,1,1,1,1,1,1,...,1,0,0,1,1,1,1,1,1,0
383009,1,0,1,1,1,1,1,1,1,1,...,1,0,0,1,1,1,1,1,1,1
383113,6,0,0,6,6,6,6,6,6,6,...,6,6,3,6,6,6,6,6,6,0
383135,2,0,0,2,2,2,2,2,2,2,...,2,2,0,2,2,2,2,2,2,0
383289,1,0,1,1,1,1,1,1,1,1,...,1,0,0,1,1,1,1,1,1,1
383439,12,0,12,12,12,12,12,12,12,12,...,12,12,6,12,12,12,12,12,12,12
383491,22,0,0,22,22,22,22,22,22,22,...,22,22,10,22,22,22,22,22,22,22
383532,10,0,10,10,10,10,10,10,10,10,...,10,10,4,10,10,10,10,10,10,10
383538,1,0,0,1,1,1,1,1,1,1,...,1,0,0,1,1,1,1,1,1,1
383540,1,0,1,1,1,1,1,1,1,1,...,1,0,0,1,1,1,1,1,1,1
383568,11,0,0,11,11,11,11,11,11,11,...,11,11,0,11,11,11,11,11,11,11
383637,4,0,0,4,4,4,4,4,4,4,...,4,4,2,4,4,4,4,4,4,0
383821,8,0,0,8,8,8,8,8,8,8,...,8,8,4,8,8,8,8,8,8,0
384033,4,0,4,4,4,4,4,4,4,4,...,4,4,2,4,4,4,4,4,4,4
384048,1,0,1,1,1,1,1,1,1,1,...,1,0,0,1,1,1,1,1,1,1
384304,1,0,1,1,1,1,1,1,1,1,...,1,0,0,1,1,1,1,1,1,1
384308,8,0,8,8,8,8,8,8,8,8,...,8,8,3,8,8,8,8,8,8,8
384386,10,0,10,10,10,10,10,10,10,10,...,10,10,5,10,10,10,10,10,10,10
384621,1,0,1,1,1,1,1,1,1,1,...,1,0,0,1,1,1,1,1,1,1
384651,7,0,0,7,7,7,7,7,7,7,...,7,7,0,7,7,7,7,7,7,7
385276,4,0,0,4,4,4,4,4,4,4,...,4,4,2,4,4,4,4,4,4,0
385600,10,0,0,10,10,10,10,10,10,10,...,10,10,5,10,10,10,10,10,0,0
385609,1,0,1,1,1,1,1,1,1,1,...,1,0,0,1,1,1,1,1,1,1
385628,2,0,0,2,2,2,2,2,2,2,...,2,0,0,2,2,2,2,2,2,0
385773,1,0,1,1,1,1,1,1,1,1,...,1,1,0,1,1,1,1,1,1,1
385888,1,0,1,1,1,1,1,1,1,1,...,1,0,0,1,1,1,1,1,1,1
386218,1,0,0,1,1,1,1,1,1,1,...,1,0,0,1,1,1,1,1,1,0
387072,1,0,0,1,1,1,1,1,1,1,...,1,0,0,1,1,1,1,1,1,0
387076,1,0,1,1,1,1,1,1,1,1,...,1,0,0,1,1,1,1,1,1,1
387078,24,0,24,24,24,24,24,24,24,24,...,24,24,8,24,24,24,24,24,24,24